#pragma once

#include <sys/types.h>
#include "glad/glad.h"

namespace gl {
enum class PARAMETER_TYPE : uint {
  DELETE = GL_DELETE_STATUS,
  LINK = GL_LINK_STATUS,
  VALIDATE = GL_VALIDATE_STATUS,

  INFO_LENGTH = GL_INFO_LOG_LENGTH,
  ATTACH = GL_ATTACHED_SHADERS,

  ATTRIBUTES = GL_ACTIVE_ATTRIBUTES,
  ATTRIBUTES_LENGTH = GL_ACTIVE_ATTRIBUTE_MAX_LENGTH,

  UNIFORMS = GL_ACTIVE_UNIFORMS,
  UNIFORMS_LENGTH = GL_ACTIVE_UNIFORM_MAX_LENGTH
};
}